import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("jarvis", {
  commitUtterance: (utterance) => ipcRenderer.invoke("utterance.commit", utterance),
  audioStart: (opts) => ipcRenderer.invoke("audio.start", opts ?? {}),
  audioStop: () => ipcRenderer.invoke("audio.stop"),
  onStream: (fn) => ipcRenderer.on("session.stream", (_e, payload) => fn(payload)),
  onDone: (fn) => ipcRenderer.on("session.done", (_e, payload) => fn(payload)),
  onCaption: (fn) => ipcRenderer.on("caption.partial", (_e, payload) => fn(payload)),
  onCaptionFinal: (fn) => ipcRenderer.on("caption.final", (_e, payload) => fn(payload)),
  onAudioError: (fn) => ipcRenderer.on("audio.error", (_e, payload) => fn(payload)),
  fleetSpawn: (task) => ipcRenderer.invoke("fleet.spawn", { task }),
  fleetList: () => ipcRenderer.invoke("fleet.list"),
  fleetStop: (sessionID) => ipcRenderer.invoke("fleet.stop", { sessionID }),
  fleetDelete: (sessionID) => ipcRenderer.invoke("fleet.delete", { sessionID }),
  permissionRespond: (requestID, decision) => ipcRenderer.invoke("permission.respond", { requestID, decision }),
  appCommand: (name, args) => ipcRenderer.invoke("app.command", { name, args }),
  settingsGet: () => ipcRenderer.invoke("settings.get"),
  onSettings: (fn) => ipcRenderer.on("settings.applied", (_e, payload) => fn(payload)),
  configConfirm: (pendingID, confirmed) => ipcRenderer.invoke("config.confirm", { pendingID, confirmed }),
  onConfigPending: (fn) => ipcRenderer.on("config.pending", (_e, payload) => fn(payload)),
  onConfigApplied: (fn) => ipcRenderer.on("config.applied", (_e, payload) => fn(payload)),
  onConfigDiscarded: (fn) => ipcRenderer.on("config.discarded", (_e, payload) => fn(payload)),
  onFleetState: (fn) => ipcRenderer.on("fleet.state", (_e, payload) => fn(payload)),
  onWorkerStream: (fn) => ipcRenderer.on("worker.stream", (_e, payload) => fn(payload)),
  onTool: (fn) => ipcRenderer.on("session.tool", (_e, payload) => fn(payload)),
  onPermission: (fn) => ipcRenderer.on("permission.waiting", (_e, payload) => fn(payload)),
  onPermissionResolved: (fn) => ipcRenderer.on("permission.resolved", (_e, payload) => fn(payload)),
});
