const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("jarvis", {
  commitUtterance: (utterance, extra) => ipcRenderer.invoke("utterance.commit", utterance, extra ?? {}),
  audioStart: (opts) => ipcRenderer.invoke("audio.start", opts ?? {}),
  audioStop: () => ipcRenderer.invoke("audio.stop"),
  onStream: (fn) => ipcRenderer.on("session.stream", (_e, payload) => fn(payload)),
  onDone: (fn) => ipcRenderer.on("session.done", (_e, payload) => fn(payload)),
  onCaption: (fn) => ipcRenderer.on("caption.partial", (_e, payload) => fn(payload)),
  onCaptionFinal: (fn) => ipcRenderer.on("caption.final", (_e, payload) => fn(payload)),
  onAudioError: (fn) => ipcRenderer.on("audio.error", (_e, payload) => fn(payload)),
  fleetSpawn: (task, directory) => ipcRenderer.invoke("fleet.spawn", { task, directory }),
  fleetList: () => ipcRenderer.invoke("fleet.list"),
  fleetStop: (sessionID) => ipcRenderer.invoke("fleet.stop", { sessionID }),
  fleetDelete: (sessionID) => ipcRenderer.invoke("fleet.delete", { sessionID }),
  permissionRespond: (requestID, decision) => ipcRenderer.invoke("permission.respond", { requestID, decision }),
  onFleetState: (fn) => ipcRenderer.on("fleet.state", (_e, payload) => fn(payload)),
  onWorkerStream: (fn) => ipcRenderer.on("worker.stream", (_e, payload) => fn(payload)),
  onTool: (fn) => ipcRenderer.on("session.tool", (_e, payload) => fn(payload)),
  onPermission: (fn) => ipcRenderer.on("permission.waiting", (_e, payload) => fn(payload)),
  onPermissionResolved: (fn) => ipcRenderer.on("permission.resolved", (_e, payload) => fn(payload)),
  sessionRename: (sessionID, title) => ipcRenderer.invoke("session.rename", { sessionID, title }),
  sessionFork: (sessionID, before) => ipcRenderer.invoke("session.fork", { sessionID, before }),
  sessionList: () => ipcRenderer.invoke("session.list"),
  sessionSwitchAgent: (sessionID, agent) => ipcRenderer.invoke("session.switchAgent", { sessionID, agent }),
  sessionSwitchModel: (sessionID, providerID, id) => ipcRenderer.invoke("session.switchModel", { sessionID, providerID, id }),
  agentList: () => ipcRenderer.invoke("agent.list"),
  modelList: () => ipcRenderer.invoke("model.list"),
  commandList: () => ipcRenderer.invoke("command.list"),
  skillList: () => ipcRenderer.invoke("skill.list"),
  sessionCommand: (sessionID, name, text) => ipcRenderer.invoke("session.command", { sessionID, name, text }),
  sessionSkill: (sessionID, id) => ipcRenderer.invoke("session.skill", { sessionID, id }),
  sessionDiff: (sessionID) => ipcRenderer.invoke("session.diff", { sessionID }),
  messageList: (sessionID) => ipcRenderer.invoke("message.list", { sessionID }),
  sessionUndo: (sessionID, messageID) => ipcRenderer.invoke("session.undo", { sessionID, messageID }),
  termStart: (command) => ipcRenderer.invoke("term.start", { command }),
  termOutput: (id, cursor) => ipcRenderer.invoke("term.output", { id, cursor }),
  termKill: (id) => ipcRenderer.invoke("term.kill", { id }),
  ptyOpen: () => ipcRenderer.invoke("pty.open"),
  ptyResize: (ptyID, rows, cols) => ipcRenderer.invoke("pty.resize", { ptyID, rows, cols }),
  ptyClose: (ptyID) => ipcRenderer.invoke("pty.close", { ptyID }),
  mcpList: () => ipcRenderer.invoke("mcp.list"),
  integrationList: () => ipcRenderer.invoke("integration.list"),
  oauthConnect: (integrationID, methodID) => ipcRenderer.invoke("oauth.connect", { integrationID, methodID }),
  oauthCancel: (integrationID, attemptID) => ipcRenderer.invoke("oauth.cancel", { integrationID, attemptID }),
  appCommand: (name, args) => ipcRenderer.invoke("app.command", { name, args }),
  settingsGet: () => ipcRenderer.invoke("settings.get"),
  onSettings: (fn) => ipcRenderer.on("settings.applied", (_e, payload) => fn(payload)),
  configConfirm: (pendingID, confirmed) => ipcRenderer.invoke("config.confirm", { pendingID, confirmed }),
  formReply: (sessionID, formID, answer) => ipcRenderer.invoke("form.reply", { sessionID, formID, answer }),
  formList: (sessionID) => ipcRenderer.invoke("form.list", { sessionID }),
  onFormWaiting: (fn) => ipcRenderer.on("form.waiting", (_e, payload) => fn(payload)),
  onFormResolved: (fn) => ipcRenderer.on("form.resolved", (_e, payload) => fn(payload)),
  onConfigPending: (fn) => ipcRenderer.on("config.pending", (_e, payload) => fn(payload)),
  onConfigApplied: (fn) => ipcRenderer.on("config.applied", (_e, payload) => fn(payload)),
  onConfigDiscarded: (fn) => ipcRenderer.on("config.discarded", (_e, payload) => fn(payload)),
  projectList: () => ipcRenderer.invoke("project.list"),
  worktreeHere: () => ipcRenderer.invoke("worktree.here"),
  worktreeList: (projectID) => ipcRenderer.invoke("worktree.list", { projectID }),
  worktreeCreate: (args) => ipcRenderer.invoke("worktree.create", args),
  worktreeRemove: (projectID, directory) => ipcRenderer.invoke("worktree.remove", { projectID, directory }),
  sessionCompact: (sessionID) => ipcRenderer.invoke("session.compact", { sessionID }),
});
